package com.hifi.redeal.theme

import androidx.compose.ui.graphics.Color

val lightPrimary = Color(0xFF1E5DAF)
val lightOnPrimary = Color(0xFFFFFFFF)
val lightPrimaryContainer = Color(0xFFD6E3FF)
val lightOnPrimaryContainer = Color(0xFF001B3E)
val lightSecondary = Color(0xFF00639B)
val lightOnSecondary = Color(0xFFFFFFFF)
val lightSecondaryContainer = Color(0xFFCEE5FF)
val lightOnSecondaryContainer = Color(0xFF001D33)
val lightTertiary = Color(0xFF006684)
val lightOnTertiary = Color(0xFFFFFFFF)
val lightTertiaryContainer = Color(0xFFBEE9FF)
val lightOnTertiaryContainer = Color(0xFF001F2A)
val lightError = Color(0xFFBA1A1A)
val lightErrorContainer = Color(0xFFFFDAD6)
val lightOnError = Color(0xFFFFFFFF)
val lightOnErrorContainer = Color(0xFF410002)
val lightBackground = Color(0xFFF8FDFF)
val lightOnBackground = Color(0xFF001F25)
val lightSurface = Color(0xFFF8FDFF)
val lightOnSurface = Color(0xFF001F25)
val lightSurfaceVariant = Color(0xFFE0E2EC)
val lightOnSurfaceVariant = Color(0xFF44474E)
val lightOutline = Color(0xFF7A7674)
val lightInverseOnSurface = Color(0xFFF5F0EE)

val darkPrimary = Color(0xFFAAC7FF)
val darkOnPrimary = Color(0xFF002F64)
val darkPrimaryContainer = Color(0xFF00458D)
val darkOnPrimaryContainer = Color(0xFFD6E3FF)
val darkSecondary = Color(0xFF97CBFF)
val darkOnSecondary = Color(0xFF003353)
val darkSecondaryContainer = Color(0xFF004A76)
val darkOnSecondaryContainer = Color(0xFFCEE5FF)
val darkTertiary = Color(0xFF68D3FF)
val darkOnTertiary = Color(0xFF003546)
val darkTertiaryContainer = Color(0xFF004D64)
val darkOnTertiaryContainer = Color(0xFFBEE9FF)
val darkError = Color(0xFFFFB4AB)
val darkErrorContainer = Color(0xFF93000A)
val darkOnError = Color(0xFF690005)
val darkOnErrorContainer = Color(0xFFFFB4AB)
val darkBackground = Color(0xFF001F25)
val darkOnBackground = Color(0xFFA6EEFF)
val darkSurface = Color(0xFF001F25)
val darkOnSurface = Color(0xFFA6EEFF)
val darkSurfaceVariant = Color(0xFF44474E)
val darkOnSurfaceVariant = Color(0xFFC4C6D0)
val darkOutline = Color(0xFF94908D)
